name: edusage
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - langchain
    - langchain_openai
    - langchain_community
    - langchain_pinecone
    - openai
    - pinecone-client
    - python-dotenv
    - pypdf
    - scikit-learn
    - numpy
